### ISSUE TITLE
Stoneholm is not loading

### ISSUE THREAD

**Issue by spinnerX49** [TheGrimsey/StoneholmForge#1]
![Screenshot 2021-04-01 142830](https://user-images.githubusercontent.com/60831375/113344958-68565d80-92f7-11eb-963d-232655f1cd3a.png)

**Comment by brisingraerowing** [comment]
Did you install [Cloth Config API (Forge)](https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge)? It's required.

**Comment by AntonTrapp** [comment]
On my system cloth-config-forge-4.1.3 is installed and I get the exact same error.

**Comment by brisingraerowing** [comment]
That is really old. The latest is 4.11.19.

**Comment by spinnerX49** [comment]
updating cloth to 4.1.1.19. fixes the issue

**Comment by AntonTrapp** [comment]
Confirmed, updating cloth fixes the problem. Hopefully everybody will google this until there is a more descriptive error message.
TNX!!!

**Comment by TheGrimsey** [comment]
I will update the mod description to say a minimum required version for ClothConfig.

Closing this as well now since you seem to have found the solution whilst I was away.
