### ISSUE TITLE
According to Blame, a template pool may have glitched

### ISSUE THREAD

**Issue by BugmanBugman** [TheGrimsey/StoneholmForge#10]
https://gist.github.com/BugmanBugman/f96d5f18e8c98dd0a17bd3d1f683ebde

**Comment by marewey** [comment]
Same here

**Comment by TheGrimsey** [comment]
Does this cause a crash or in any way seem to do anything in game?

**Comment by brisingraerowing** [comment]
I've been getting this and it causes the game to hang, requiring killing the process.

**Comment by TheGrimsey** [comment]
> 
> 
> I've been getting this and it causes the game to hang, requiring killing the process.

Do you have a crashlog? Or just the latest log from when you need to kill the process?

**Comment by brisingraerowing** [comment]
I'll get one in a moment.

**Comment by brisingraerowing** [comment]
[Latest Log](https://gist.github.com/BrisingrAerowing/bff0fa5f168da9dad9090c842fd9ff68)

Also, there were two structure errors at the bottom of the log this time:

```
****************** Blame Report Structure NBT 1.16.5-3.2.5-forge ******************

 Failed to load structure nbt file from:  minecraft:2x3_3
 The path represented by this is:  data/minecraft/structures/2x3_3.nbt
 Most common cause is that there is a typo in this path to the nbt file.
 Please let the mod author know about this so they can double check to make sure the path is correct.
 A common mistake is putting the structure nbt file in the asset folder when it needs to go in data/structures folder.

[04Aug2021 09:54:42.835] [Worker-Main34/ERROR] [com.telepathicgrunt.blame.Blame/]: 
****************** Blame Report Structure NBT 1.16.5-3.2.5-forge ******************

 Failed to load structure nbt file from:  minecraft:empty
 The path represented by this is:  data/minecraft/structures/empty.nbt
 The calling Template Pool is: stoneholm:hallways/hallway_x
 Most common cause is that there is a typo in this path to the nbt file.
 Please let the mod author know about this so they can double check to make sure the path is correct.
 A common mistake is putting the structure nbt file in the asset folder when it needs to go in data/structures folder.
```

**Comment by TheGrimsey** [comment]
> 
> 
> [Latest Log](https://gist.github.com/BrisingrAerowing/bff0fa5f168da9dad9090c842fd9ff68)
> 
> Also, there were two structure errors at the bottom of the log this time:
> 
> ```
> ****************** Blame Report Structure NBT 1.16.5-3.2.5-forge ******************
> 
>  Failed to load structure nbt file from:  minecraft:2x3_3
>  The path represented by this is:  data/minecraft/structures/2x3_3.nbt
>  Most common cause is that there is a typo in this path to the nbt file.
>  Please let the mod author know about this so they can double check to make sure the path is correct.
>  A common mistake is putting the structure nbt file in the asset folder when it needs to go in data/structures folder.
> 
> [04Aug2021 09:54:42.835] [Worker-Main34/ERROR] [com.telepathicgrunt.blame.Blame/]: 
> ****************** Blame Report Structure NBT 1.16.5-3.2.5-forge ******************
> 
>  Failed to load structure nbt file from:  minecraft:empty
>  The path represented by this is:  data/minecraft/structures/empty.nbt
>  The calling Template Pool is: stoneholm:hallways/hallway_x
>  Most common cause is that there is a typo in this path to the nbt file.
>  Please let the mod author know about this so they can double check to make sure the path is correct.
>  A common mistake is putting the structure nbt file in the asset folder when it needs to go in data/structures folder.
> ```

Well, reading that log there is also a ton of JEI exceptions as well as some other blame errors:
´´´
****************** Blame Report Broken Worldgen 1.16.5-3.2.5-forge ******************

 These ConfiguredFeature were unabled to be turned into JSON which is... bad.
 This is all the info we can get about the ConfiguredFeature

 Error msg is: Unknown registry element com.endertech.minecraft.mods.adlods.deposit.DepositGenerator@47931cab
 Registry Name: null
´´´

I do not see a reason why it would your issue would be related to Stoneholm.

As for the main subject of this report. minecraft:empty is an empty structure created from code in Minecraft code. I don't think blame is correct in reporting it.
