### ISSUE TITLE
Empty template pool or something

### ISSUE THREAD

**Issue by Kutomi1** [TheGrimsey/StoneholmForge#11]
According to Blame, ****************** Blame Report 1.16.5-3.2.2-forge ******************

 Failed to load structure nbt file from:  minecraft:empty
 The path represented by this is:  data/minecraft/structures/empty.nbt
 The calling Template Pool is: stoneholm:poi/bedroom_cross
 Most common cause is that there is a typo in this path to the nbt file.
 Please let the mod author know about this so they can double check to make sure the path is correct.
 A common mistake is putting the structure nbt file in the asset folder when it needs to go in data/structures folder.

**Comment by TheGrimsey** [comment]
Is there a crash log or?

**Comment by Kutomi1** [comment]
it didn't crash

**Comment by TheGrimsey** [comment]
Then this is just Blame not realising that minecraft:empty is a structure created from in Mojang code.

Closing as this isn't really a problem with Stoneholm.
