### ISSUE TITLE
[1.18.1] Stoneholm Villages doesn't contain any villagers. At all.

### ISSUE THREAD

**Issue by Gbergz** [TheGrimsey/StoneholmForge#14]
Title ^ 
No villagers are part of the structure, it's like a ghost town down there.

**Minecraft**: 1.18.1
**Forge**: 39.0.45
**Stoneholm**: 1.4 | https://www.curseforge.com/minecraft/mc-mods/stoneholm-forge/files/3613471

**-** Gbergz

**Comment by Cakx** [comment]
I encountered exactly the same issue on the same versions as the user above.
I was only using this Mod and the required Lib.

I checked 4 underground villages, only Cows, Creepers & Zombies were found in their respective rooms but no Villagers at all. 

 - Cakx

**Comment by DieDaily** [comment]
I'm seeing the same issue on the **1.18.2** version of the mod on my server. Initially I thought there might be some chance that these underground villages spawn deserted, which I thought was a cool touch. However, I've visited 5 of them at this point and all of them are devoid of villagers. Standard above ground villages are appropriately populated.

The mod appears to work fine, though, in a single player game. If there are any logs I can provide that can help resolve the problem please reply and I'll do what I can.

**Comment by TheGrimsey** [comment]
> Title ^ No villagers are part of the structure, it's like a ghost town down there.
> 
> **Minecraft**: 1.18.1 **Forge**: 39.0.45 **Stoneholm**: 1.4 | https://www.curseforge.com/minecraft/mc-mods/stoneholm-forge/files/3613471
> 
> **-** Gbergz

This should be resolved by updating to a newer version of forge.



> I'm seeing the same issue on the **1.18.2** version of the mod on my server. Initially I thought there might be some chance that these underground villages spawn deserted, which I thought was a cool touch. However, I've visited 5 of them at this point and all of them are devoid of villagers. Standard above ground villages are appropriately populated.
> 
> The mod appears to work fine, though, in a single player game. If there are any logs I can provide that can help resolve the problem please reply and I'll do what I can.

This is not related to this.
