### ISSUE TITLE
[1.18.1] Crashes on startup with the latest Fabric API

### ISSUE THREAD

**Issue by mtb-xt** [TheGrimsey/StoneholmForge#15]
Hey, I've updated my fabric API mod to fix some biome generation issues in Modern Industrialization and now minecraft crashes and points at stoneholm as a possible reason.

See crash log - https://crashy.net/HLfcWwQ8Jzs3DQ8wE3Qz

**Comment by TheGrimsey** [comment]
I released a small update (1.4.2). Was your issue fixed?

**Comment by mtb-xt** [comment]
@TheGrimsey  Yes, thank you!
