### ISSUE TITLE
Stoneholm villages are being affected by Hostile Villages

### ISSUE THREAD

**Issue by SpencerMeow** [TheGrimsey/StoneholmForge#16]
Forge 1.16.5. Basically I want the Hostile Villages mod to only affect normal surface villages, but instead it is also affecting underground villages. Isn't there any way to avoid this happening

**Comment by TheGrimsey** [comment]
No. Giving a glance at Hostile Villages it is "All Rights Reserved". It's as far as I am concerned a black box in how it works. You'd have to speak with them.

1.16.5 is also not a version I support. Haven't released an update for it since 1.17 released.
