### ISSUE TITLE
biome blacklist

### ISSUE THREAD

**Issue by zachsai** [TheGrimsey/StoneholmForge#2]
![image](https://user-images.githubusercontent.com/63996164/113525074-dbbed000-9580-11eb-99d8-f9e15779965e.png)
I suggest adding a biome blacklist using the forge biome dictionary for all ocean biomes

**Comment by TheGrimsey** [comment]
Interesting, I was trying to replicate what the fabric version does and only register to biomes of certain categories (as seen [here](https://github.com/TheGrimsey/StoneholmForge/blob/main/src/main/java/net/thegrimsey/stoneholm/Stoneholm.java#L66)).

Will investigate for next version though.

**Comment by brisingraerowing** [comment]
I saw this in one of my packs, but it stopped happening after removing a couple mods, so I think some mod is screwing with biome stuff here.

**Comment by TheGrimsey** [comment]
Shouldn't be an issue in current versions. Additionally, water-related issues have been solved for villages.
