### ISSUE TITLE
wont load right

### ISSUE THREAD

**Issue by stuff360** [TheGrimsey/StoneholmForge#3]
i am useing the forge version and it is not working
![Screen Shot 2021-04-12 at 11 27 43 AM](https://user-images.githubusercontent.com/82408215/114443041-1aa4e500-9b82-11eb-84a3-5856f8cdf0a7.png)
![Screen Shot 2021-04-12 at 11 29 42 AM](https://user-images.githubusercontent.com/82408215/114443301-622b7100-9b82-11eb-8a5a-f4fd76767e80.png)

**Comment by TheGrimsey** [comment]
You are missing Cloth Config.

https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge/

**Comment by stuff360** [comment]
how do install it. i am on the forge version on a mac?

**Comment by TheGrimsey** [comment]
You install it exactly as you installed Stoneholm. Either through curseforge or by dropping the cloth config jar into your mods folder directly.

**Comment by stuff360** [comment]
oh. ok. THANK YOU SO MUCH. I LOVE THIS MOD
