### ISSUE TITLE
Is Stockholm Underground VIllages compatible with Yungs Better Strongholds?

### ISSUE THREAD

**Issue by koderian** [TheGrimsey/StoneholmForge#4]
Yungs Better Strongholds released today and I wanted to know if this mod, Stockholm Villages is compatible with Yungs Better Strongholds. 

https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds

**Comment by gglobensky** [comment]
I ran some quick tests and they seem to be. Stoneholm are still normal strongholds and Yung's Better Strongholds are there too.

**Comment by TheGrimsey** [comment]
Stoneholm structures are separate from Strongholds and shouldn't be affected by changes to strongholds at all.

**Comment by koderian** [comment]
I dunno if this is possible with your mod, but can you include a way for Stockholm strongholds to work in Yungs Better Strongholds? So villages can spawn in Better Strongholds as well?

**Comment by TheGrimsey** [comment]
They don't spawn in Strongholds now. They style is inspired by strongholds but they are completely separate from them.

**Comment by koderian** [comment]
Oh, okay thanks. Closing issue!
