### ISSUE TITLE
Path Error with newer updates

### ISSUE THREAD

**Issue by zachsai** [TheGrimsey/StoneholmForge#5]
Hi, you changed something with the structure for data and entities. There is no longer an iron golem.nbt where we could include mobs to spawn in the structure.
![image](https://user-images.githubusercontent.com/63996164/116301971-a156e600-a76e-11eb-85d8-1287c4e4fa58.png)

Please fix this so we can add back custom mobs to the structure through the iron golem.nbt

**Comment by TheGrimsey** [comment]
Oh yeah that is an error on my part. I am working on an update that should be ready by the end of the week. Will fix this as well.

**Comment by TheGrimsey** [comment]
This was fixed with 1.2.
