### ISSUE TITLE
Stoneholms not generating correctly.

### ISSUE THREAD

**Issue by ghost** [TheGrimsey/StoneholmForge#7]
I don't know if its my fault or not but i found a stoneholm generated with water everywhere, in particular water spawning inside blocks like stairs, walls, and chests.
I could think its my fault cause i have a world generator mod and it may be breaking stoneholms generations but i did some tests early and this didn't happened.
(Info: MC 1.16.5 / Forge 36.1.13 / Latest mod release)

**Comment by ghost** [comment]
Update: I tried to find the problem and i think its the fact that it generated inside a river (the portion on it with water is corresponding at the one being inside the river).
![2021-05-05_01 45 06](https://user-images.githubusercontent.com/83294912/117082909-b5d54880-ad43-11eb-8bc3-cbc4285b1811.png)

**Comment by TheGrimsey** [comment]
Aye this has to do with Minecraft generation.

I can't seem to find a way to fix it currently which is why by default they don't spawn in any wet biomes.

**Comment by TheGrimsey** [comment]
> 
> 
> Update: I tried to find the problem and i think its the fact that it generated inside a river (the portion on it with water is corresponding at the one being inside the river).
> ![2021-05-05_01 45 06](https://user-images.githubusercontent.com/83294912/117082909-b5d54880-ad43-11eb-8bc3-cbc4285b1811.png)

The fact that it is so high up is another issue though. May I have the seed for this world?

**Comment by ghost** [comment]
Hi again, so if u want i can try to recreate this with and without the generator mod to be sure its not my fault, by the way i did some screenshots too if you'd like them.
Seed:1772609852839529583

**Comment by BugmanBugman** [comment]
![2021-05-07_10 07 36](https://user-images.githubusercontent.com/40730042/117499068-4e381c80-af40-11eb-9502-e4dba50ea870.png)
same issue happened to me, I don't have the seed on hand but if it happens I'll send you it

**Comment by TheGrimsey** [comment]
Fixes for water were in 1.3.

Fix for generating in the air is coming in next release.
