### ISSUE TITLE
[1.16.5 Enhancement] Use Vanilla Entity NBT Files

### ISSUE THREAD

**Issue by Dradon7** [TheGrimsey/StoneholmForge#8]
Your villages use unnessesary NBT files. Vanilla includes nbt files for farm animals, villagers, armor stands, and iron golems. You don't need to add your own. As an added bonus, any mod/datapack that changes to those vanilla nbt files now have semicompatability with Stoneholm

The biggest example that I can think of is Guard Villagers. By using the vanilla iron golem nbt, Guards automatically spawn in stoneholm villages, and if you don't have the Guard Villagers mod installed, there's no change whatsoever.

**Comment by Dradon7** [comment]
Actually, looking through the fabric version, they use vanilla's entity files for everything except the custom llamas, so you could consider this feature parity.

**Comment by TheGrimsey** [comment]
> 
> 
> Actually, looking through the fabric version, they use vanilla's entity files for everything except the custom llamas, so you could consider this feature parity.

No they don't. They use exactly the same data. You gotta check the V1.2 branch.

**Comment by TheGrimsey** [comment]
I switched from using the vanilla villager NBTs in 1.2 because they wouldnt reliably spawn villagers and villages would end up empty. I don't think I will switch back.
